### PR TITLE
Restore allow_writeable_chroot option

### PR DESCRIPTION
**Pull request by erobhal**
For some reason allow_writeable_chroot were removed in commit 0068efd. This patch adds it back to the template.

### CODE REVIEW

**Comment by erobhal** [comment]
Travis CI seems to fail randomly and I don't understand why. This patch passed in this build:
https://travis-ci.org/erobhal/puppet-vsftpd/builds/265537126

**Comment by erobhal** [comment]
Ping @Phil-Friderici

**Comment by Phil-Friderici** [comment]
Hej guys, I have fixed the spec testing rig in PR https://github.com/gillarkod/puppet-vsftpd/pull/12.

**Comment by Phil-Friderici** [comment]
Fixed in PR https://github.com/gillarkod/puppet-vsftpd/pull/12, released in 1.0.4, thanks gents :)

**Pull request closed without merging**
