### PR TITLE
Restore allow_writeable_chroot option (working with erobhal)

### PR DESCRIPTION
**Pull request by Phil-Friderici**
trying to fix testing issues found in PR https://github.com/gillarkod/puppet-vsftpd/pull/11

### CODE REVIEW

**Review by anders-larsson — APPROVED** [review]
Looks good to me

**Comment by Phil-Friderici** [comment]
Thanks @anders-larsson for the review :)

**Comment by Phil-Friderici** [comment]
Released in 1.0.4, thanks gents :)

**Comment by erobhal** [comment]
Thank you

**Pull request merged**
